### ISSUE TITLE
Leaderboard responsive design issue 

### ISSUE THREAD

**Issue by Rohith-JN** [Rohith-JN/type-frontend#2]
Fix leaderboard table responsive design issue on mobile 

![image](https://github.com/Rohith-JN/type-frontend/assets/78314165/b23c53fb-ec1c-404b-b0ae-d168e0f6f28b)

**Comment by ItamarTati** [comment]
I think I know how to solve this but I can't find your html page index.html

**Comment by ItamarTati** [comment]
https://stackoverflow.com/questions/22732475/div-width-100-percent-not-working-in-mobile-browser

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
<head>

**Comment by shaharyair** [comment]
I would be happy to fix it !

**Comment by Rohith-JN** [comment]
@shaharyair sure go ahead, to test the site locally, you will have to clone both the backend and frontend, setup the environment variables for both the repos, setup postgres-db along with the tables. I know its a bit too much to configure but will simplify it later. Will update the repo with an env.example file.

**Comment by shaharyair** [comment]
> @shaharyair sure go ahead, to test the site locally, you will have to clone both the backend and frontend, setup the environment variables for both the repos, setup postgres-db along with the tables. I know its a bit too much to configure but will simplify it later. Will update the repo with an env.example file.

Alright no problem let me know when you added the env.example

**Comment by Rohith-JN** [comment]
@ItamarTati, it's a next.js site so the code is in tsx, which is in the pages directory. For now I will try to solve this issue myself using the stackoverflow link you provided since getting to test the site locally is going to be a hassle
