### ISSUE TITLE
Partially typedWord doesn't get counted when test is completed

### ISSUE THREAD

**Issue by Rohith-JN** [Rohith-JN/type-frontend#4]
When the timer is about to reach 0, if a word is partially typed, then the characters from the word is not counted. 
The function that handles the test logic: [utils/test.ts](https://github.com/Rohith-JN/type-frontend/blob/main/utils/test.ts)

**Comment by shreeup** [comment]
Please help to review this pull request - https://github.com/Rohith-JN/type-frontend/pull/10

**Comment by Rohith-JN** [comment]
Thank you for the PR, will take a look
