### ISSUE TITLE
Migrate to react-hot-toast

### ISSUE THREAD

**Issue by Rohith-JN** [Rohith-JN/type-frontend#8]
Currently there is a UI issue with `react-toastify` that hasn't been resolved yet, due to no response on this issue I have decided to migrate to `react-hot-toast`

**Comment by mohibkay** [comment]
Hey, @Rohith-JN, could you please assign this issue to me?
I would like to work on migrating the toast to react-hot-toast.

**Comment by Rohith-JN** [comment]
Sure @mohibkay

**Comment by Rohith-JN** [comment]
Realized it was a mistake on my side and resolved the UI issue by importing react-toastify styles in `_app.tsx`, turns out stylesheet of react-toastify was being totally removed when changing route
